### PR TITLE
Allow user to sort issue #1013

### LINKED ISSUE #1013: Allow user to sort issue
Sort issues on the issues explorer table.

### PR DESCRIPTION
**Pull request by Precious-Macaulay**
# Pull Request Template

> Closes #1013

### Sorting Functionality:
- Added sorting functionality to make it easier for users to organize and find tasks based on different criteria.
- Introduced dynamic sorting for each column (Task, Status, Project, Value, Labels, Created At).
- Implemented ascending and descending sorting based on user preferences.

### Code Structure and Readability:
- Refactored the code for better readability and maintainability.
- Introduced metadata for table headers to enhance code organization.

## Purpose
The purpose of this pull request is to enhance the task table component by introducing sorting functionality for better organization and dynamic sorting based on user preferences. Additionally, the code structure has been refactored to improve readability and maintainability.

## Solution
The solution involves implementing sorting capabilities for each column in the task table, allowing users to efficiently organize and find tasks. Dynamic sorting is introduced, along with code refactoring to enhance code readability and maintainability. Metadata for table headers is now utilized to improve code organization.

## Screenshots
[711315c6-10b8-4ea0-82de-cbeda3b1f3f4.webm](https://github.com/worknenjoy/gitpay/assets/87583799/6ba89a1d-b62f-4608-90a0-a6f51527a1bb)

[711315c6-10b8-4ea0-82de-cbeda3b1f3f4.webm](https://github.com/worknenjoy/gitpay/assets/87583799/53be8951-c84d-49ea-b7a0-150b6f63d5ea)

## Checklist
- [x] Code has been tested and works as intended
- [x] Properly documented code
- [x] Follows coding standards and guidelines
- [x] All tests pass
- [x] No conflicts with the current codebase
- [ ] Code has been reviewed by at least one other team member

## Related Issues
Closes #1013

## Additional Notes
- Ensured that the sorting functionality is thoroughly tested under various scenarios.
- Reviewers, please pay attention to the changes in code structure and provide feedback on readability.

### CODE REVIEW

**Comment by Precious-Macaulay** [comment]
Codacy Static Code Analysis  is due to destructuring of which is part of the initial code style

**Comment by Precious-Macaulay** [comment]
@oleksandr-shvets Please review my latest commit

**Comment by alexanmtz** [comment]
Hey @Precious-Macaulay , thanks for reviewing the solution; it seems to work in most cases now.

Just one thing I would like to request to have it fully working and with a good experience is to provide a way to reset the filters, so when you click the first time, it sorts up, then it sorts down, and In the third option it should reset, it would be possible to do it so we can have the original order again.

**Comment by oleksandr-shvets** [comment]
You cat try to create `pmd.xml` file in project root to Exclude UnnecessaryBlock rule
```xml
<?xml version="1.0"?>
<ruleset name="Custom Rules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0
                            http://pmd.sourceforge.net/ruleset_2_0_0.xsd">

    <!-- Exclude UnnecessaryBlock rule for JavaScript -->
    <rule ref="category/java/errorprone.xml">
        <exclude name="UnnecessaryBlock"/>
    </rule>

</ruleset>
```

**Comment by Precious-Macaulay** [comment]
i merged the improved table to my existing sorting code

**Comment by alexanmtz** [comment]
@Precious-Macaulay there's an error for me when I checked out your branch, please verify your console.

**Comment by Precious-Macaulay** [comment]
Yes my branch started lagging behind in commits and there was a merge conflict based on the improved table commit

**Comment by Precious-Macaulay** [comment]
i will be closing this pull request due to merge issue and i will create a new pull request with all sorting funtionality implemented

**Pull request closed without merging**
