### PR TITLE
Feature/payment header s ummary

### LINKED ISSUE #227: Better flow to let contributors know about paypal and direct payments
We will add extra info in the task view page

### Level
Beginner

### Current behavior
- We are facing a issue about the payment, the user isn't aware about how method the payment for a bounty was, and for this there's issues to activate the account. The screenshot is self explanatory, we need more info about that bounty. We have all the information, but this make it clear on the interface

### Expected behavior
Expected to show extra info about the task

### Screenshots
screen shot 2018-12-22 at 1 22 33 am

task-details

### PR DESCRIPTION
**Pull request by robertkibet**
## Description

> Updated payment component, added a payment header that updates bounty information if bounty exists

## Changes

- two files: task-header and within Card directory, all within client side(frontend)

## Issue

> closes #227

## Impacted Area

> Single Task Dashboard

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create/Import an Issue from gitpay account
- You should be able to see updated bounty from the header section if there is a set bounty, and blank if it does not exist

image

image

### CODE REVIEW

**Comment by alexanmtz** [comment]
Thanks for the changes @robertkibet, I tested and the interface seems good 👍 

You need to check the code formatting that caused the build to fail:
https://circleci.com/gh/worknenjoy/gitpay/1396?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Probably you can fix with `npm run lint-fix`

**Comment by robertkibet** [comment]
> Thanks for the changes @robertkibet, I tested and the interface seems good 
> 
> You need to check the code formatting that caused the build to fail:
> https://circleci.com/gh/worknenjoy/gitpay/1396?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
> 
> Probably you can fix with `npm run lint-fix`

aha, cool cool, will have this checked in the next few hrs :+1:

**Comment by alexanmtz** [comment]
Hello @robertkibet, the build is still failing:
https://circleci.com/gh/worknenjoy/gitpay/1404?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

And I see some changes related to docker, please just send changes related to your changes. Maybe you're not sync with the mainstream master

**Comment by robertkibet** [comment]
> Hello @robertkibet, the build is still failing:
> https://circleci.com/gh/worknenjoy/gitpay/1404?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
> 
> And I see some changes related to docker, please just send changes related to your changes. Maybe you're not sync with the mainstream master

doing this `npm run lint-fix` effected those changes on the other files @alexanmtz

**Comment by alexanmtz** [comment]
So I think you will need to fix manually @robertkibet on the files you changed with `npm run lint`

**Comment by alexanmtz** [comment]
Hello @robertkibet, there's was other files not related to the feature breaking the build still, but I did the changes and if you look into the commit here I had to complete the issue with some extra details.

You can always from a branch checkout file from master with the command:
`git checkout origin/master -- docker-compose.test.yml` like I did in this example to checkout from master the docker-compose.test.yml that was modified for some reason.

Maybe you miss syncing the master from the fork with the upstream master.

Here's the commit so you know what it was missing to complete this:
https://github.com/worknenjoy/gitpay/pull/629/commits/04399c798bac1baa2736e85d30944d5fff5cb1e6

So now we can merge your changes 👍

**Comment by robertkibet** [comment]
@alexanmtz aha, that is Perfect :raised_hands: :tada:  thanks

> Hello @robertkibet, there's was other files not related to the feature breaking the build still, but I did the changes and if you look into the commit here I had to complete the issue with some extra details.
> 
> You can always from a branch checkout file from master with the command:
> `git checkout origin/master -- docker-compose.test.yml` like I did in this example to checkout from master the docker-compose.test.yml that was modified for some reason.
> 
> Maybe you miss syncing the master from the fork with the upstream master.
> 
> Here's the commit so you know what it was missing to complete this:
> [04399c7](https://github.com/worknenjoy/gitpay/commit/04399c798bac1baa2736e85d30944d5fff5cb1e6)
> 
> So now we can merge your changes

**Comment by robertkibet** [comment]
[Ship has sailed](https://media1.tenor.com/images/10375cb05171ad92e030f5c5da8e47c9/tenor.gif?itemid=6074692)

**Pull request merged**
