### PR TITLE
Create team.js

### LINKED ISSUE #547: A model for teams
We should create a model to have teams with names, and teams have many users.

### Why
We will start to organize users in teams to have better control of permissions later on.

### Level
Beginner

### PR DESCRIPTION
**Pull request by arpit9667**
## Description

> Added model for the Team

## Issue

> Closes #547 

## Impacted Area

> Main page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create a team containing the users.

### CODE REVIEW

**Comment by alexanmtz** [comment]
Great @arpit9667, but we have an issue when run the migration:
https://circleci.com/gh/worknenjoy/gitpay/1403?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

```
Unhandled rejection SequelizeBaseError: column "TeamId" does not exist
```

**Comment by arpit9667** [comment]
@alexanmtz How to run the migration? I have created the migration for Team but the table is not getting created in the database. 
migraion
model


`

**Comment by alexanmtz** [comment]
@arpit9667 you can run the migration with `npm run migrate`

**Comment by arpit9667** [comment]
@alexanmtz 
The last two migration files are not running. 
== One for the Plans Table
== One for the Teams Table
I think this is the problem. Can you check please?
Screenshot from 2020-05-06 18-03-36

**Comment by alexanmtz** [comment]
@arpit9667 , if you run the migration already, you would need to drop the database and create again to run from scratch

**Comment by alexanmtz** [comment]
@arpit9667, there's changes on `Plan` model that should not be included.

Maybe you're not in sync with the upstream master.

**Comment by arpit9667** [comment]
@alexanmtz I found out that there was some error in the migration file for the Plans table, so I corrected it. That was the reason that the migrations were not running. Also, should I add a TeamId column to the Users Table?

**Comment by alexanmtz** [comment]
Thanks for the update @arpit9667, but it seems that makes sense the user be able to join many teams

**Comment by alexanmtz** [comment]
@arpit9667 yeah, the `package-lock.json` should not be included on the commit, because there's no new library installed, you should commit only the files required for this PR, otherwise, we may have conflict when merging.

You can maybe check the file from master (needs to be an updated master) with `git checkout master -- package-lock.json` (I think, please research about it).

**Pull request closed without merging**
