### PR TITLE
Issue #222

### PR DESCRIPTION
**Pull request by VictorAlessander**
## Description

> Refactor task invite and task interested to task assignment.

## Changes

- Task interested and task invite

## Issue

> #222

## Impacted Area

> Task page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create / log user
- Create Task
- Invite someone to join the task that was already created
- Set interested to task

> image

> image

### CODE REVIEW

**Comment by VictorAlessander** [comment]
Understood. My bad.
Soon I will update the PR with a suggestion of change.

**Comment by VictorAlessander** [comment]
What you think about this approach? @alexanmtz 

image

**Comment by alexanmtz** [comment]
Great @VictorAlessander, you can proceed with this solution 🎉 

Just change the order to: _Add bounty_, _Invite_, _Invite sponsor_ and _I'm interested_

**Comment by VictorAlessander** [comment]
@alexanmtz , I forgot to ask: The button will be visible only if the user logged is the owner of task?

**Comment by VictorAlessander** [comment]
I setup the SendGrid and I could receive the e-mail and see the layout.
Would you mind to evaluate if layout satisfies the requirements?

image

**Comment by alexanmtz** [comment]
Great @VictorAlessander! We should display the button if the user is logged, otherwise, we should display the login. We need this because we send on the email who invited. Are you doing this check? 

So I think we're almost there. The texts for this e-mail subject should be "You're invited to fund an issue on Gitpay"

And the text on the headline of the dialog should be as the layout:

"Invite someone to add bounties to this issue"

74260537-f4738300-4cf9-11ea-9e13-4e0fd4520b10

**Comment by VictorAlessander** [comment]
Yes, I used the existent check.

`!props.logged`

So, just to confirm, any user logged can use the funding feature, right?

@alexanmtz PR updated.

**Comment by alexanmtz** [comment]
@VictorAlessander, yes, any logged user can use the feature.

I tested and the flow is right, by showing the login dialog, but we need to change the text here:
Screen Shot 2020-03-23 at 9 21 53 AM

We should use "You need to log in to invite someone"

And I think you reused the component, so let's make this as a parameter to be able to use in different places.

And once you log in, the user should be redirected to the original page. Take a look at the login component, there's a way to pass the referrer to redirect after login.

**Comment by VictorAlessander** [comment]
@alexanmtz I tried to pass the title of dialogs as props but throws an error.
Could you help me to understand what possibly I'm doing wrong?

image


For the others considerations, I updated the PR.

**Comment by alexanmtz** [comment]
@VictorAlessander the value on id attribute needs to be static. So let's keep static with generic information like "Invite someone to be part of this issue", and we will not need props anymore and having a more generic component.

**Comment by VictorAlessander** [comment]
Understood. I kept static.

**Comment by alexanmtz** [comment]
@VictorAlessander and the next thing (I hope the last) is the email validation, it should send just with a valid mail, so we need to validate the field. You can use our notification components to do it in a easy way

**Comment by VictorAlessander** [comment]
I realized that exists this same validation in others components (like login-form component), so I used the validation/notification provided by Material UI.
This could be valid to satisfy the requirement of e-mail validation?

image

PS: If still have some things that I missed, please, tell me so I will fix.

**Comment by alexanmtz** [comment]
Great solution @VictorAlessander 👍

**Pull request merged**
