### PR TITLE
Paul Onyekwelu - fixing of Duplicated user on the user interested tab

### PR DESCRIPTION
**Pull request by silanka007**
#517  Duplicated user on the user interested tab 

> Description of the pull request
fixing of Duplicated user on the user interested tab so that if a user is to submit  to be interested to work on a particular issue more than once, this will not produce duplicate record.

## Changes
implementation of a conditional check if a user (by userId and taskId) already exist in an array of assigns for a particular task.

- Where your changes apply
changes were made in taskUpdate.js file

## Issue
Duplicated user on the user interested tab 
> #517 

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue
- run app
-Create a user - user1
-Import an issue with the user1
-Create another user - user2
-Apply to solve that issue created by user1 from user2
- Apply again
- Only a single entry will be recorded.

### CODE REVIEW

**Comment by alexanmtz** [comment]
@silanka007, what happen if the user is interested again? It will ignore the second time or it will update the entry? Cause this user maybe can send a different entry, so it should update to the last one.

For example:

User apply and suggest $20, then the same user apply again and suggest $40. What is gonna happen in this case?

**Comment by silanka007** [comment]
@alexanmtz  for for late reply. there was a power outage and response was really power. I was able to power up a little. when a user is interested again it ignores the second time. there is no update.

**Comment by silanka007** [comment]
@alexanmtz Good day sir. I was able to refactor the code so that the offer is updated whether or not an Assign already exist.

**Comment by alexanmtz** [comment]
Great @silanka007, there's just an issue with a conflict on `package-lock.json`. As you didn't install any new library, we should not change this file. So you should check out from the original master branch. Let me know if you need any help.

**Comment by silanka007** [comment]
@alexanmtz  sorry sir I don't understand what you mean by checking out from the original master branch. should I git merge and then pull request from the forked master branch?

**Comment by silanka007** [comment]
I checkout the master branch then reset the duplicate branch to initial, delete the remote package-lock.json files, installed node 8.6.0 using nvm and rerun the application. I hope the conflict has resolved sir?

**Comment by alexanmtz** [comment]
@silanka007 the `package-lock.json` should remain the same from the original master (upstream master), if you check your PR still have changes on `package-lock.json`, there's no conflict anymore, but they have a lot of changes. I'm afraid this could break something.

You need to sync your fork with our master. Then merge into your branch.

If you have too much trouble, you can maybe get just your changes and create a new PR with the diff from `modules/tasks/taskUpdate.js`

Actually you can create a patch from the diffs from this file and apply this diff in a new branch.

**Pull request closed without merging**
