### PR TITLE
Stats page UI Improvement

### PR DESCRIPTION
**Pull request by sep2001aryan**
## Description

> Previously ugly looking stats page is redefined to look more elegant 

## Changes

- changes apply to the Stats page

## Issue

> Closes #677 

## Impacted Area

> Stats page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- simply head toward the {url}/stats link to see the stats page

image

### CODE REVIEW

**Comment by alexanmtz** [comment]
Great @sep2001aryan we only have now one conflict in `package-lock.json`

**Comment by sep2001aryan** [comment]
Ok i will fix it in a minute

**Comment by sep2001aryan** [comment]
image
I don't know why build is failing

**Comment by alexanmtz** [comment]
@sep2001aryan you can't delete `package-lock.json`, you should solve the conflict, and in order to do so, you will need to sync your branch with the upstream master.

**Comment by alexanmtz** [comment]
Great @sep2001aryan 🎉

**Comment by sep2001aryan** [comment]
I tried to resolve the conflict by deleting the package-lock.json and adding it again instead of updating it and it worked this time 🤧🤧

**Pull request merged**
