### PR TITLE
Allow user sort

### LINKED ISSUE #1013: Allow user to sort issue
Sort issues on the issues explorer table.

### PR DESCRIPTION
**Pull request by Precious-Macaulay**
# Pull Request Template

> Closes #1013

### Sorting Functionality:
- Added sorting functionality to make it easier for users to organize and find tasks based on different criteria.
- Introduced dynamic sorting for each column (Task, Status, Project, Value, Labels, Created At).
- Implemented ascending and descending sorting based on user preferences with reset sort on third click

### Code Structure and Readability:
- Refactored the code for better readability and maintainability.
- Introduced metadata for table headers to enhance code organization.

## Purpose
The purpose of this pull request is to enhance the task table component by introducing sorting functionality for better organization and dynamic sorting based on user preferences. Additionally, the code structure has been refactored to improve readability and maintainability.

## Solution
The solution involves implementing sorting capabilities for each column in the task table, allowing users to efficiently organize and find tasks. Dynamic sorting is introduced, along with code refactoring to enhance code readability and maintainability. Metadata for table headers is now utilized to improve code organization.

## Screenshots

[f33ec271-37d7-4b7d-8c31-4f7667448956.webm](https://github.com/worknenjoy/gitpay/assets/87583799/df1ad247-251a-4d61-a64f-aeecfa1cf099)

[42a2866e-f097-486f-8486-f251e64d0d53.webm](https://github.com/worknenjoy/gitpay/assets/87583799/647f6cb8-c71b-488e-938e-4cb0dcc6f50d)

## Checklist
- [x] Code has been tested and works as intended
- [x] Properly documented code
- [x] Follows coding standards and guidelines
- [x] All tests pass
- [x] No conflicts with the current codebase
- [ ] Code has been reviewed by at least one other team member

## Related Issues
Closes #1013

## Additional Notes
- Ensured that the sorting functionality is thoroughly tested under various scenarios.
- Reviewers, please pay attention to the changes in code structure and provide feedback on readability.

### CODE REVIEW

**Comment by Precious-Macaulay** [comment]
@alexanmtz I have updated the code

**Comment by Precious-Macaulay** [comment]
Alright i will work on that now

**Comment by Precious-Macaulay** [comment]
Also @alexanmtz is there away i can populate my local database to test everything before pushing since migration and seeding only creates 3 task and nothing on the other filters tabs

**Comment by alexanmtz** [comment]
> Also @alexanmtz is there away i can populate my local database to test everything before pushing since migration and seeding only creates 3 task and nothing on the other filters tabs

@Precious-Macaulay you can edit the seed to have more tasks, or manually add tasks yourself. You can use my test repository do import issues: https://github.com/alexanmtz/test-repository

We have our front-end tests that you can use to unit test the component, but I guess it would take longer and not required now.

**Comment by Precious-Macaulay** [comment]
> @Precious-Macaulay still not seeing any record on the table when we filter on other tabs: pageshot of 'Gitpay - Bounties for git issues solved' @ 2024-02-23-1306'08
> 
> And when I tested on the value table along with issues with no bounties, the sorting fails, try to cover this case too.
> 
> Can you please check these issues?
@alexanmtz 
I have checked all issue
1. not seeing any record on the table -- it is because there is no record, when i imported an issue i could the record got updated and i could see the issues
the actual problem was that the conditional component to render when "no issues " was not returned of which i have fixed.
2.  for this And when I tested on the value table along with issues with no bounties, the sorting fails, try to cover this case too. --- no bounties means the values is 0 so they all maintain their position when sorted since they all have same value.

Additional update is that i handled the null, date and label sorting better to ensure better precision in sorting.


Screenshot (24)


Screenshot (25)

**Comment by alexanmtz** [comment]
Great @Precious-Macaulay, now it's working great 💯 

Let's merge it and thanks for all your effort to get the final result 🥇

**Comment by Precious-Macaulay** [comment]
You're welcome!
I look forward to more contribution.😊

**Pull request merged**
