### PR TITLE
Send weekly task with the label "Weekly digest"

### LINKED ISSUE #559: Send weekly task with the label "Weekly digest"
When setting a label "Weekly Digest", add this issue as part of a special weekly digest.

### Why
When we want to highlight issues we can add to a weekly digest

### Level
Medium

### PR DESCRIPTION
**Pull request by khoded**
## Description

> A cron job to send email notifications to all users on tasks with label weekly digest

## Changes

- cron.js
- server.js
- modules/mail/task.js
- locales

## Issue

> Closes #559

## Impacted Area

> weekly cron jobs

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Signup/login as user
- import an issue on with label 'Weekly digest'
- Edit cron time to test immediately

### CODE REVIEW

**Comment by alexanmtz** [comment]
Hey @khoded, we're almost there 🎉 

Do you think you're able to create the automated tests to check this feature?

**Comment by khoded** [comment]
Ohh yes definitely, I'm writing them together with the other features will drop the PRs this week.

**Comment by alexanmtz** [comment]
Hey @khoded, any updates on this?

**Comment by khoded** [comment]
@alexanmtz  i have added the weekly digest test. A test case on the Ordercron seems to be failing the build the check. but weekly digest is done

**Comment by khoded** [comment]
Ohh  I will correct that now

**Pull request closed without merging**
