### PR TITLE
#557 Open for Jobs checkbox for users

### LINKED ISSUE #557: Open for jobs checkbox
Add a checkbox and an attribute on the User model which record if the user is open for job opportunities

### Why
Users with this option activated will have a chance to receive job proposals from their contribution

### Level
Beginner

### How to reproduce the user scenario
 - Create a user
 - Go to user preferences

### PR DESCRIPTION
**Pull request by nikhil-sachdeva**
## Description

> Open for Jobs checkbox for users on the preferences page.

## Changes

- Checkbox added

## Issue

> Closes #557 

## Impacted Area

> Preferences Page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create user
- Go to preferences

### CODE REVIEW

**Comment by nikhil-sachdeva** [comment]
@alexanmtz I have added the migration as well. Kindly look into it.

**Comment by alexanmtz** [comment]
@nikhil-sachdeva please check the build with lint errors:
https://circleci.com/gh/worknenjoy/gitpay/1399?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

Probably you can fix with `npm run lint-fix`

**Comment by nikhil-sachdeva** [comment]
Builds have also passed. Thanks for the guidance.

**Comment by alexanmtz** [comment]
Great @nikhil-sachdeva 👍

**Pull request merged**
