### PR TITLE
Add loader

### PR DESCRIPTION
**Pull request by etfaghaoubeid**
## Description
 create loader component , implement loader logic in app component

> Description of the pull request

## Changes

- frontend/src/main.app , frontend/src/components/loader

## Issue

> Closes #593 

## Impacted Area

> Main page

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create / loader component
- Create Task
- Other steps

### CODE REVIEW

**Comment by alexanmtz** [comment]
@etfaghaoubeid thanks for update your solution with this new PR. Now seems technically good, but check your solution deployed here: https://gitpay-loader-bkthu24jqxbtzdy6.herokuapp.com/#/

It's a big circular progress on the left top. Could you please improve this to a smaller loading with our main color centralized on the screen?

**Comment by etfaghaoubeid** [comment]
Ok

**Comment by alexanmtz** [comment]
excelent @etfaghaoubeid 💯

**Comment by etfaghaoubeid** [comment]
Next step ?

**Comment by alexanmtz** [comment]
@etfaghaoubeid, we will contact you with the details, once we evaluate the candidates, it's a feedback and the next step if we proceed with the interview.

**Pull request merged**
