### PR TITLE
Account settings

### LINKED ISSUE #535: Change account settings
A new item on a user account to change their account settings. The menu have an item _Settings_ and the user will be able to connect from Github, Bitbucket or local account and change settings.

### Why
We need a way to change the initial settings from that user

### Level
Beginner

### Screenshot attached
change-account

### How to reproduce the user scenario
 - Create an account. We should have an account setting item on the user account page menu

### What you will need to complete this issue
You will need the Github and Bitbucket development keys to log and we will send once you're assigned.

### PR DESCRIPTION
**Pull request by namandangi**
## Description

> Add Account Settings page

## Changes

- Account Settings 

## Issue

> Closes #535 

## Changes

> ``` /profile/account-settings ```

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create & log in
- Visit url ``` /profile/account-settings```
- Use provider buttons for Github?Bitbucket
- Or for updating local account, fill in the details and check the privacy policy checkbox and click the update account button
- For updating any fields of the local account, the old password and the privacy-policy checkbox are mandatory
- The new password field and confirm password field must have the same value

image

image
image

### CODE REVIEW

**Comment by alexanmtz** [comment]
@namandangi, I think we have in this PR code related to the User roles, so you should have this branch of account settings from the original master and this should come from different branches.

**Comment by namandangi** [comment]
Yeah actually my master branch got merged with the user roles branch so that's why they have a common history and that is why it got reflected in the account settings branch

**Comment by namandangi** [comment]
> @namandangi, I think we have in this PR code related to the User roles, so you should have this branch of account settings from the original master and this should come from different branches.

@alexanmtz user roles is a part of pull #666 and without it Account settings doesnt work , I found this today while cherry-picking

**Comment by alexanmtz** [comment]
Ok @namandangi, let's consider the #666 then and close this one 👍

**Pull request closed without merging**
