### PR TITLE
Fixed issue #655 'Adjust button text'

### LINKED ISSUE #655: Adjust button text
Button text is broken

### Why
Improve reading

### Level
Beginner

### Current behavior
Buttons of bounty area have broken texts

### Expected behavior
Need to pass another text or adjust button size 

### Useful links
https://gitpay.me/#/task/339

### Screenshot attached
some screenshot
image
image

### How to reproduce the user scenario
Access the link and scroll down to see the buttons on the right side

### PR DESCRIPTION
**Pull request by djl218**
## Description
The text of the buttons in the bounty area was wrapping.  Now the text is on one line.

## Changes
The change was to /frontend/src/components/task/task.js on line #257.

## Issue
Closes #655 

## Before
https://prnt.sc/v5phtn

## After
https://prnt.sc/v5pc24

### CODE REVIEW

**Comment by alexanmtz** [comment]
Great @djl218, thanks for the contribution. I think maybe it would be risky to update Webpack in the same PR, but let's proceed and test. Next time try to send only the change in the issue scope and any update we can do in another PR, so it's easier to test.

**Comment by djl218** [comment]
Oops sorry @alexanmtz, didn't mean to do that.  I thought that only made that commit on my local branch.  Still learning how this stuff works.

**Comment by alexanmtz** [comment]
That's ok, @djl218, you did a great job! 💯 

You can improve your Git knowledge here :-)

There's another open issue for this release with a bounty of $20:
https://github.com/worknenjoy/gitpay/issues/518

Here to apply to receive the bounty:
https://gitpay.me/#/task/394

Let me know if you're interested

**Comment by djl218** [comment]
Cool thanks! How does the bounty system work?  Would I get paid if I figure it out?  Cause that's pretty cool lol.  

Maybe in a couple of days I could take a look at it or maybe another issue.  I am trying to pace myself and do one contribution a week.  Have to balance it with courses that I am taking.  Working towards getting my first developer job.

I like this project.  It's a pretty decent-sized react project that has issues that I feel are appropriate for my skill level.  It's been kinda tough to find projects to match my skill level.  I tried looking at repos from FAANG companies, but couldn't find anything that seemed my level.  Gitpay seems like a pretty good fit for me at the moment.

**Comment by alexanmtz** [comment]
Hey @djl218, there are some open-source issues to collaborate on, and some with bounties, like the one I presented:
https://gitpay.me/#/task/394

Now that's one developer assigned to receive the bounties when the Pull Request is merged.

And that's ok, just check on Gitpay.me the ones available when you wish. And that's good that you could solve the issue and that you felt comfortable to work on it. We want to help developers to get confident to contribute and be part of a platform of work that they can be part of.

So yeah, you can start to challenge yourself with Gitpay and explore other bounties and open source projects to improve your skills and work with real projects.

**Pull request merged**
