### PR TITLE
Welcome user component

### LINKED ISSUE #534: Welcome user
A wizard when the user creates an account 

### Why
A warm welcome to our user and basic instructions

### Level
Beginner

### Screenshot attached
Mobile3
Mobile2
Mobile1
welcome-main-screen

### Assets
Group 2
Group 4
Group 5

### How to reproduce the user scenario
 - Create a user
 - A first-time welcome should display the wizard

### Tips
Look for #266

### PR DESCRIPTION
**Pull request by Simran-Chaudhary**
## Created a welcome user component 

> Added a new component to session folder called welcome-user.js

## Added a call to welcomeUser in login-page.js and a new component named WelcomeUser

- login-page.js, welcome-user.js, welcome1.png, welcome2.png, welcome3.png

## 534

> Closes #534 

## Impacted Area

> Welcome user popup

## Steps to test

Steps needed to reproduce the scenario from this change to validate if the pull request solve this issue

- Create user
- Once user is created successfully, a welcome dialogue page appears

## First step doesn't have previous
Screenshot 2020-09-05 at 12 43 14
## Welcome user appears only first time on welcome page
Screenshot 2020-09-05 at 12 59 55

## Last step (added finish button that closes the dialogue box)
Screenshot 2020-09-05 at 12 55 43

### CODE REVIEW

**Review by alexanmtz — CHANGES_REQUESTED** [review]
Great @Simran-Chaudhary 👍 

the welcome user is at the login page, and it should be once the user log successfully and we need to show only once, probably using `LocalStorage`

But that's good that you did as a component, so it will be better to refactor your code.

So please check your code so we can do a better user interaction, and allow this welcome page at the login.

And the `Welcome` component should close when we reach the last step.

**Comment by Simran-Chaudhary** [comment]
@alexanmtz alright! So once I sign up the sign in page shows up. So instead of showing after sign-up we should show it on sign-in (the first time) ? And I see the wizard is used elsewhere also so I'll make it reusable and use this component in both the places so we can remove some code.

**Comment by alexanmtz** [comment]
@Simran-Chaudhary yes, it should be on the first sign-in, it would be great 👍 

And yeah, the Welcome component follows the same standard of the existing wizard, so it would be a plus make as one component too 💯

**Comment by Simran-Chaudhary** [comment]
@alexanmtz  I've made the requested changes.
The refactoring to create a reusable component , I'll raise a separate pr so reviewing becomes easier.

**Comment by alexanmtz** [comment]
Great @Simran-Chaudhary, you will send everything in the other PR, we should close this one?

**Comment by Simran-Chaudhary** [comment]
We could merge this one as it has all the functionality. The other pr will just be refactoring to remove the existing wizard(one similar to welcome user) and use this existing component.

**Review by alexanmtz — APPROVED** [review]
Great @Simran-Chaudhary 👍

**Comment by alexanmtz** [comment]
@Simran-Chaudhary we're just not limiting for a user, so if I log with two users on the same computer, I will just see once. But that's ok for now, it's an extreme case and not even necessary, so we're good to go 🎉

**Comment by Simran-Chaudhary** [comment]
@alexanmtz yes I actually noticed this too so I thought I would store the userid or email but in the existing code I saw things like isFirstTask etc were not user specific. So did the same here. Maybe we could have a bug to attach user id wherever we're storing user specific information in localStorage so that it stays consistent throughout the application.

**Pull request merged**
